// ---- WASM Component Model Patterns in Rust ----
//
// This crate demonstrates the core concepts of the WASM Component Model:
//   1. WIT-inspired interface traits
//   2. Guest implementation (WASM module)
//   3. Host runtime (wasmtime-like)
//   4. Component composition
//
// Compiles natively for testing. Same code can target wasm32 with
// `cargo build --target wasm32-unknown-unknown` or `wasm32-wasip2`.

// ---------------------------------------------------------------------------
// 1. WIT Interface Definitions (translated to Rust traits)
//
// In practice, these are generated by `wit-bindgen` from .wit files like:
//
// ```wit
// // math.wit
// package example:math;
//
// interface types {
//     record matrix {
//         data: list<f32>,
//         rows: u32,
//         cols: u32,
//     }
// }
//
// world inference {
//     export matmul: func(a: matrix, b: matrix) -> matrix;
//     export relu: func(x: matrix) -> matrix;
// }
// ```
// ---------------------------------------------------------------------------

use std::fmt;

/// A simple matrix type — maps to WIT `record matrix`
#[derive(Clone, Debug, PartialEq)]
pub struct Matrix {
    pub data: Vec<f32>,
    pub rows: u32,
    pub cols: u32,
}

impl Matrix {
    pub fn new(data: Vec<f32>, rows: u32, cols: u32) -> Self {
        assert_eq!(data.len() as u32, rows * cols);
        Matrix { data, rows, cols }
    }

    pub fn zeros(rows: u32, cols: u32) -> Self {
        Matrix {
            data: vec![0.0; (rows * cols) as usize],
            rows,
            cols,
        }
    }

    pub fn get(&self, r: u32, c: u32) -> f32 {
        self.data[(r * self.cols + c) as usize]
    }

    pub fn set(&mut self, r: u32, c: u32, val: f32) {
        self.data[(r * self.cols + c) as usize] = val;
    }
}

impl fmt::Display for Matrix {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for r in 0..self.rows {
            write!(f, "[")?;
            for c in 0..self.cols {
                if c > 0 {
                    write!(f, ", ")?;
                }
                write!(f, "{:6.2}", self.get(r, c))?;
            }
            writeln!(f, "]")?;
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// 2. Guest Interface — what the WASM component exports
// ---------------------------------------------------------------------------

pub trait MathGuest {
    fn matmul(&self, a: &Matrix, b: &Matrix) -> Result<Matrix, String>;
    fn relu(&self, x: &Matrix) -> Matrix;
    fn softmax(&self, x: &Matrix) -> Matrix;
}

// ---------------------------------------------------------------------------
// 3. Host Interface — what the WASM component imports from the host
// ---------------------------------------------------------------------------

pub trait MathHost {
    fn log(&self, message: &str);
    fn random_f32(&self) -> f32;
}

// ---------------------------------------------------------------------------
// 4. Guest Implementation — compiled into the WASM module
// ---------------------------------------------------------------------------

pub struct WasmGuest;

impl MathGuest for WasmGuest {
    fn matmul(&self, a: &Matrix, b: &Matrix) -> Result<Matrix, String> {
        if a.cols != b.rows {
            return Err(format!(
                "shape mismatch: {}x{} vs {}x{}",
                a.rows, a.cols, b.rows, b.cols
            ));
        }
        let m = a.rows;
        let k = a.cols;
        let n = b.cols;
        let mut result = Matrix::zeros(m, n);
        for i in 0..m {
            for j in 0..n {
                let mut sum = 0.0;
                for t in 0..k {
                    sum += a.get(i, t) * b.get(t, j);
                }
                result.set(i, j, sum);
            }
        }
        Ok(result)
    }

    fn relu(&self, x: &Matrix) -> Matrix {
        let data: Vec<f32> = x.data.iter().map(|&v| v.max(0.0)).collect();
        Matrix::new(data, x.rows, x.cols)
    }

    fn softmax(&self, x: &Matrix) -> Matrix {
        let mut data = x.data.clone();
        for r in 0..x.rows {
            let start = (r * x.cols) as usize;
            let end = start + x.cols as usize;
            let max_val = data[start..end]
                .iter()
                .cloned()
                .fold(f32::NEG_INFINITY, f32::max);
            let mut sum = 0.0;
            for i in start..end {
                let e = (data[i] - max_val).exp();
                data[i] = e;
                sum += e;
            }
            for i in start..end {
                data[i] /= sum;
            }
        }
        Matrix::new(data, x.rows, x.cols)
    }
}

// ---------------------------------------------------------------------------
// 5. Host Runtime — simulates a WASM runtime like wasmtime
//
// In production, this would be wasmtime loading the compiled .wasm component.
// Here we demonstrate the same pattern using trait dispatch.
// ---------------------------------------------------------------------------

pub struct HostRuntime<G: MathGuest, H: MathHost> {
    guest: G,
    host: H,
}

impl<G: MathGuest, H: MathHost> HostRuntime<G, H> {
    pub fn new(guest: G, host: H) -> Self {
        HostRuntime { guest, host }
    }

    /// Run a full inference pipeline: matmul → relu → softmax
    pub fn run_inference(&self, input: &Matrix, weight: &Matrix, bias: &Matrix) -> Result<Matrix, String> {
        self.host.log("=== WASM component inference ===");

        self.host.log("  step 1: matmul(input, weight)");
        let z = self.guest.matmul(input, weight)?;

        self.host.log("  step 2: add bias");
        let z_plus_b = add_matrices(&z, bias);

        self.host.log("  step 3: relu activation");
        let a = self.guest.relu(&z_plus_b);

        self.host.log("  step 4: softmax output");
        let out = self.guest.softmax(&a);

        self.host.log("  === inference complete ===");
        Ok(out)
    }

    /// Verify matmul result inside the "WASM sandbox"
    pub fn verify_matmul(&self, a: &Matrix, b: &Matrix, expected: &Matrix) -> Result<bool, String> {
        let result = self.guest.matmul(a, b)?;
        Ok(approx_equal(&result, expected, 1e-6))
    }
}

// ---------------------------------------------------------------------------
// 6. Host Implementations
// ---------------------------------------------------------------------------

pub struct ConsoleLogger;

impl MathHost for ConsoleLogger {
    fn log(&self, message: &str) {
        println!("[host] {}", message);
    }

    fn random_f32(&self) -> f32 {
        // In a real WASM host, this would call wasi:random/random
        static mut SEED: u32 = 42;
        unsafe {
            SEED = SEED.wrapping_mul(1_103_515_245).wrapping_add(12_345);
            (SEED as f32) / (u32::MAX as f32)
        }
    }
}

// ---------------------------------------------------------------------------
// 7. Component Composition — chaining multiple WASM components
// ---------------------------------------------------------------------------

pub struct Pipeline<A: MathGuest, B: MathGuest> {
    component_a: A,
    component_b: B,
}

impl<A: MathGuest, B: MathGuest> Pipeline<A, B> {
    pub fn new(component_a: A, component_b: B) -> Self {
        Pipeline { component_a, component_b }
    }

    /// Compose two components: first A processes, then B processes the result
    pub fn compose(&self, a: &Matrix, b: &Matrix) -> Result<Matrix, String> {
        let mid = self.component_a.matmul(a, b)?;
        Ok(self.component_b.relu(&mid))
    }
}

// ---------------------------------------------------------------------------
// 8. Utility
// ---------------------------------------------------------------------------

fn add_matrices(a: &Matrix, b: &Matrix) -> Matrix {
    assert_eq!(a.rows, b.rows);
    assert_eq!(a.cols, b.cols);
    let data: Vec<f32> = a.data.iter().zip(b.data.iter()).map(|(x, y)| x + y).collect();
    Matrix::new(data, a.rows, a.cols)
}

fn approx_equal(a: &Matrix, b: &Matrix, eps: f32) -> bool {
    if a.rows != b.rows || a.cols != b.cols {
        return false;
    }
    a.data.iter().zip(b.data.iter()).all(|(x, y)| (x - y).abs() < eps)
}

// ---------------------------------------------------------------------------
// 9. WASM-compatible utilities (use #[cfg(target_arch = "wasm32")] in real code)
// ---------------------------------------------------------------------------

/// A WASM-compatible memory buffer (linear memory abstraction)
pub struct LinearMemory {
    data: Vec<u8>,
}

impl LinearMemory {
    pub fn new(size: usize) -> Self {
        LinearMemory {
            data: vec![0; size],
        }
    }

    pub fn read_f32(&self, offset: usize) -> f32 {
        let bytes: [u8; 4] = self.data[offset..offset + 4].try_into().unwrap();
        f32::from_le_bytes(bytes)
    }

    pub fn write_f32(&mut self, offset: usize, val: f32) {
        let bytes = val.to_le_bytes();
        self.data[offset..offset + 4].copy_from_slice(&bytes);
    }

    pub fn size(&self) -> usize {
        self.data.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_matmul_2x2() {
        let guest = WasmGuest;
        let a = Matrix::new(vec![1.0, 2.0, 3.0, 4.0], 2, 2);
        let b = Matrix::new(vec![5.0, 6.0, 7.0, 8.0], 2, 2);
        let c = guest.matmul(&a, &b).unwrap();
        assert!((c.get(0, 0) - 19.0).abs() < 1e-6);
        assert!((c.get(0, 1) - 22.0).abs() < 1e-6);
        assert!((c.get(1, 0) - 43.0).abs() < 1e-6);
        assert!((c.get(1, 1) - 50.0).abs() < 1e-6);
    }

    #[test]
    fn test_matmul_shape_mismatch() {
        let guest = WasmGuest;
        let a = Matrix::new(vec![1.0, 2.0, 3.0, 4.0], 2, 2);
        let b = Matrix::new(vec![1.0, 2.0, 3.0], 3, 1);
        let result = guest.matmul(&a, &b);
        assert!(result.is_err());
    }

    #[test]
    fn test_relu() {
        let guest = WasmGuest;
        let x = Matrix::new(vec![-1.0, 0.0, 2.0, -3.0], 2, 2);
        let r = guest.relu(&x);
        assert!((r.get(0, 0) - 0.0).abs() < 1e-6);
        assert!((r.get(0, 1) - 0.0).abs() < 1e-6);
        assert!((r.get(1, 0) - 2.0).abs() < 1e-6);
        assert!((r.get(1, 1) - 0.0).abs() < 1e-6);
    }

    #[test]
    fn test_softmax() {
        let guest = WasmGuest;
        let x = Matrix::new(vec![1.0, 2.0, 3.0], 1, 3);
        let s = guest.softmax(&x);
        let sum: f32 = s.data.iter().sum();
        assert!((sum - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_host_runtime_inference() {
        let guest = WasmGuest;
        let host = ConsoleLogger;
        let runtime = HostRuntime::new(guest, host);

        let input = Matrix::new(vec![0.5, -0.3, 0.8, 0.1], 2, 2);
        let weight = Matrix::new(vec![0.1, 0.2, 0.3, 0.4], 2, 2);
        let bias = Matrix::new(vec![0.01, 0.02, 0.03, 0.04], 2, 2);

        let result = runtime.run_inference(&input, &weight, &bias).unwrap();
        assert_eq!(result.rows, 2);
        assert_eq!(result.cols, 2);

        // Softmax output should sum to 1 per row
        let row0_sum: f32 = (0..2).map(|c| result.get(0, c)).sum();
        assert!((row0_sum - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_verify_matmul() {
        let guest = WasmGuest;
        let host = ConsoleLogger;
        let runtime = HostRuntime::new(guest, host);

        let a = Matrix::new(vec![1.0, 0.0, 0.0, 1.0], 2, 2);
        let b = Matrix::new(vec![1.0, 2.0, 3.0, 4.0], 2, 2);
        let expected = Matrix::new(vec![1.0, 2.0, 3.0, 4.0], 2, 2);

        assert!(runtime.verify_matmul(&a, &b, &expected).unwrap());
    }

    #[test]
    fn test_component_composition() {
        let comp_a = WasmGuest;
        let comp_b = WasmGuest;
        let pipeline = Pipeline::new(comp_a, comp_b);

        let a = Matrix::new(vec![1.0, 2.0, 3.0, 4.0], 2, 2);
        let b = Matrix::new(vec![5.0, 6.0, 7.0, 8.0], 2, 2);

        let result = pipeline.compose(&a, &b).unwrap();
        // matmul result then relu (all positive, so same)
        assert!((result.get(0, 0) - 19.0).abs() < 1e-6);
        assert!((result.get(1, 1) - 50.0).abs() < 1e-6);
    }

    #[test]
    fn test_linear_memory() {
        let mut mem = LinearMemory::new(1024);
        mem.write_f32(0, 3.14);
        assert!((mem.read_f32(0) - 3.14).abs() < 1e-6);
        assert_eq!(mem.size(), 1024);
    }

    #[test]
    fn test_matrix_display() {
        let m = Matrix::new(vec![1.0, 2.0, 3.0, 4.0], 2, 2);
        let s = format!("{}", m);
        assert!(s.contains("1.00"));
        assert!(s.contains("2.00"));
    }
}
